name: Convert Tutorials to Markdown

on:
  push:
    branches: [ main ]
    paths: [ 'tutorials/**' ]
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  convert-tutorials:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat nbconvert
        
    - name: Convert tutorials to markdown
      run: |
        python convert_ipynb_to_md.py
        
    - name: Commit converted files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/tutorials/
        git diff --staged --quiet || git commit -m "Auto-convert tutorials to markdown [skip ci]"
        git push
